version: '2'
services:
  db:
    image: "postgres:9"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
