"""empty message

Revision ID: 2d9eca7e7688
Revises: 
Create Date: 2020-01-18 21:06:32.448700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9eca7e7688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acronym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acronym_key', sa.Text(), nullable=True),
    sa.Column('acronym_definition', sa.Text(), nullable=True),
    sa.Column('user_id_created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acronym_acronym_key'), 'acronym', ['acronym_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acronym_acronym_key'), table_name='acronym')
    op.drop_table('acronym')
    # ### end Alembic commands ###
