"""empty message

Revision ID: 5b69f2f7110c
Revises: 2d9eca7e7688
Create Date: 2020-01-19 20:01:17.560688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b69f2f7110c'
down_revision = '2d9eca7e7688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acronym', sa.Column('user_created_by', sa.Text(), nullable=True))
    op.drop_column('acronym', 'user_id_created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acronym', sa.Column('user_id_created_by', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('acronym', 'user_created_by')
    # ### end Alembic commands ###
